ATTACK:
  BanditsPrior:
    run: false
    path: attacks\\BanditsPrior\\BanditsPrior.py
    max_queries: 1000
    fd_eta: 0.01
    image_lr: 0.5
    online_lr: 0.1
    mode: l2
    exploration: 0.01
    tile_size: 50
    epsilon: 5.0
    nes: false
    gradient_iters: 1
    batch_size: 5

  CornerSearch:
    run: false
    path: attacks\\CornerSearch\\CornerSearch.py
    type_attack: L0+sigma
    n_iter: 100
    n_max: 10
    kappa: -1
    epsilon: -1
    sparsity: 10
    size_incr: 1
    batch_size: 5
  DDN:
    run: false
    path: attacks\\DDN\\DDN.py
    steps: 1000
    targeted: false
    gamma: 0.05
    init_norm: 1.0
    quantize: true
    levels: 256
    batch_size: 5

  DeepFool:
    run: false
    path: attacks\\DeepFool\\DeepFool.py
    overshoot: 0.02
    max_iter: 50

  GeoDA:
    run: false
    path: attacks\\GeoDA\\GeoDA.py
    dist: linf
    tol: 0.0001
    sigma: 0.0002
    mu: 0.6
    delta: 255
    search_space: sub
    sub_dim: 75
    Q_max: 5000
    batch_size: 5

  LogBarrier:
    run: false
    path: attacks\\LogBarrier\\LogBarrier.py
    norm: 2
    lower_bound: 0
    upper_bound: 1
    dt: 0.01
    alpha: 0.1
    beta: 0.75
    gamma: 0.5
    max_outer: 15
    tol: 1e-6
    max_inner: 100
    T: 500
    batch_size: 5

  SimBA:
    run: false
    path: attacks\\SimBA\\SimBA.py
    freq_dims: 14
    stride: 7
    epsilon: 0.2
    linf_bound: 0.0
    order: rand
    targeted: false
    log_every: 1
    num_iters: 0
    pixel_attack: true
    batch_size: 5

  UAP:
    run: false
    path: attacks\\UAP\\UAP.py
    overshoot: 0.02
    xi: 10
    delta: 0.2
    max_iter_df: 10
    max_iter_uni: 1000
    norm: inf
    batch_size: 5

  SquareAttack:
    run: false
    path: attacks\\SquareAttack\\SquareAttack.py
    eps: 5
    n_iters: 1000
    p_init: 0.05
    targeted: false
    constraint: linf
    batch_size: 5

  AutoAttack:
    run: false
    path: attacks/AutoAttack/run_autoattack.py
    batch_size: 250 #250
    eps: 0.03137254901960784
    norm: Linf
    version: standard
 
  SQBA:
    run: true
    path: attacks/SQBA/SQBA.py
    q_budget: 100 # lower for faster runs
    batch_size: 250
    surrogate_model: 'DenseNet121'

  TEA:
    run: true
    path: attacks/TEA/TEA.py
    batch_size: 100 #250
    q_budget_global: 150
    q_budget_patch: 150
    initial_step_factor: 0.0001
    step_size_factor: 0.005
    momentum: 0.9
    targeted: false
    target_label: 1
    use_cgba_refinement: true #for further refinment, if we wanna spend more queries
    refinement_attack_method: CGBA_H # CGBA_H or CGBA_S
    refinement_dim_reduc_factor: 6 #4
    refinement_iteration: 10 #93
    refinement_initial_query: 4 #30
    refinement_tol: 0.001
    refinement_sigma: 0.002

  DSA:
    run: true
    path: attacks/DSA/DSA.py
    surrogate_models: "DenseNet121,GoogLeNet, ResNet"
    targeted: false
    q_budget: 1000 #4000
    eps: 0.03137254901960784 #0.0627
    constraint: linf 
    target_label: 1
    batch_size: 64
  
  DiffAttack:
    run: true
    path: attacks/DiffAttack/DiffAttack.py
    train_autoencoders: false
    surrogate_models: "DenseNet121,ResNet,MobileNet"
    ae_epochs: 30 #20
    ae_batch_size: 8 #64
    ae_lr: 0.0001 #0.0001
    ae_input_size: 224
    ae_pgd_eps: 0.05 #0.03137254901960784  # 8/255
    ae_pgd_alpha: 0.00784313725490196 # 2/255
    ae_pgd_steps: 30
    ae_pgd_batch_size: 4
    ae_train_fraction: 0.01
    amp: true
    ae_device: cuda
    pop_chunk: 2

    #black box attack params
    q_budget: 1000 #250
    targeted: false
    target_label: 1
    eps: 0.03137254901960784 #0.05 #0.03137254901960784
    npop: 10
    sigma: 0.1
    sigma_f: 0.1
    lr: 0.01
    innermargin: 5.0
